name: Daily Commit

on:
  schedule:
    - cron: '30 2 * * *'  # Runs daily at 08:00 AM IST (UTC 02:30)
  workflow_dispatch:  # Allows manual trigger

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Add commit by 24ds2000065@ds.study.iitm.ac.in"
        run: |
          echo "Daily commit: $(date -u)" >> daily-log.txt
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add daily-log.txt
          git commit -m "Daily commit at $(date -u)"
          git push
