name: Email Action Test

on:
  push:
    branches:
      - main  # or your default branch
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 24ds2000065@ds.study.iitm.ac.in
        run: echo "Hello, world!"
